---
- name: Set variables
  set_fact:
    path:  "{{ ansible_env.PATH }}:/usr/local/bin"
    r_libs: "{{ ansible_env.HOME }}/.clir/r/library"
    clir_root: "{{ ansible_env.HOME }}/.clir"
    clir: "{{ ansible_env.HOME }}/.clir/bin/clir"

- name: Check R command
  environment:
    PATH: "{{ path }}"
  shell: |
    R --version

- name: Check .clir
  stat:
    path: "{{ clir_root }}"
  register: clir_st

- name: Clone clir
  git:
    repo: 'https://github.com/dceoy/clir.git'
    dest: "{{ ansible_env.HOME }}/.clir"
  notify: Notify updates of R via Slack

- name: Install clir
  when: not clir_st.stat.exists
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir_root }}/install.sh
  notify: Notify updates of R via Slack

- name: Set cran repositories
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir }} set-cran {{ item }}
  with_items:
    - "{{ r_repos.cran }}"
  notify: Notify updates of R via Slack

- name: Set drat repositories
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir }} set-drat {{ item }}
  with_items:
    - "{{ r_repos.drat }}"
  notify: Notify updates of R via Slack

- name: Install and update cran packages
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir }} cran-install --quiet {{ item }}
  with_items:
    - "{{ r_packages.cran }}"
    - "{{ r_packages.drat }}"
  ignore_errors: true
  notify: Notify updates of R via Slack

- name: Install and update github packages
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir }} github-install --quiet {{ item }}
  with_items:
    - "{{ r_packages.github }}"
  ignore_errors: true
  notify: Notify updates of R via Slack

- name: Install and update bioconductor packages
  environment:
    PATH: "{{ path }}"
    R_LIBS: "{{ r_libs }}"
  shell: |
    {{ clir }} bioc-install --quiet {{ item }}
  with_items:
    - "{{ r_packages.bioconductor }}"
  ignore_errors: true
  notify: Notify updates of R via Slack
