---
- name: Set variables
  set_fact:
    path: "{{ ansible_env.PATH }}:/usr/local/bin"
    r_libs: "{{ ansible_env.HOME }}/.clir/r/library"
    clir: "{{ ansible_env.HOME }}/.clir/bin/clir"
    install_clir_sh: '/tmp/install_clir.sh'

- name: Check R command
  environment:
    PATH: "{{ path }}"
  shell: |
    R --version
  changed_when: false

- name: Download the installer of clir
  get_url:
    url: 'https://raw.githubusercontent.com/dceoy/clir/master/install.sh'
    dest: "{{ install_clir_sh }}"

- name: Install or update clir
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    bash {{ install_clir_sh }}
  notify: Notify updates of R via Slack

- name: Remove the installer
  file:
    path: "{{ install_clir_sh }}"
    state: absent

- name: Set cran repositories
  when:
    - r_repos is defined
    - r_repos.cran is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} cran {{ item }}
  with_items: "{{ r_repos.cran }}"
  notify: Notify updates of R via Slack

- name: Set drat repositories
  when:
    - r_repos is defined
    - r_repos.drat is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} drat {{ item }}
  with_items: "{{ r_repos.drat }}"
  notify: Notify updates of R via Slack

- name: Install and update cran packages
  when:
    - r_repos is defined
    - r_repos.cran is defined
    - r_packages is defined
    - r_packages.cran is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} install --devt=cran --quiet {{ item }}
  with_items:
    - "{{ r_packages.cran }}"
  ignore_errors: true
  notify: Notify updates of R via Slack

- name: Install and update drat packages
  when:
    - r_repos is defined
    - r_repos.drat is defined
    - r_packages is defined
    - r_packages.drat is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} install --devt=cran --quiet {{ item }}
  with_items: "{{ r_packages.drat }}"
  ignore_errors: true
  notify: Notify updates of R via Slack

- name: Install and update github packages
  when:
    - r_packages is defined
    - r_packages.github is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} install --devt=github --quiet {{ item }}
  with_items: "{{ r_packages.github }}"
  ignore_errors: true
  notify: Notify updates of R via Slack

- name: Install and update bioconductor packages
  when:
    - r_packages is defined
    - r_packages.bioconductor is defined
  environment:
    PATH: "{{ path }}"
    R_LIBS_USER: "{{ r_libs }}"
  shell: |
    {{ clir }} install --devt=bioc --quiet {{ item }}
  with_items: "{{ r_packages.bioconductor }}"
  ignore_errors: true
  notify: Notify updates of R via Slack
