---
npm_packages:
  - ajv-cli
  - eslint
  - eslint-config-airbnb
  - eslint-plugin-import
  - eslint-plugin-toml
  - jsonlint
  - markdownlint
  - npx
  - puppeteer
  - serverless
  - typescript
  - yarn
