---
brew_packages:
  from_third_party_repos:
    - tap: weaveworks/tap
      name:
        - eksctl
    - tap: aws/tap
      name:
        - aws-sam-cli
  with_options:
    - name: cairo
      options:
        - with-x11
    - name: imagemagick
      options:
        - with-fontconfig
        - with-librsvg
    - name: vim
      options:
        - with-lua
        - with-python3
  without_options:
    - atk
    - amazon-ecs-cli
    - autoconf
    - automake
    - awscli
    - bazel
    - bats-core
    - bcftools
    - bedtools
    - binutils
    - boost
    - bwa
    - cabal-install
    - circleci
    - cloudformation-guard
    - colordiff
    - conjure-up
    - coreutils
    - corkscrew
    - curl
    - diffutils
    - dvc
    - ed
    - elixir
    - fcrackzip
    - fd
    - ffmpeg
    - findutils
    - freetds
    - freetype
    - fribidi
    - gawk
    - gcc
    - gdal
    - gdbm
    - gflags
    - ghc
    - git
    - glog
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnu-which
    - gnutls
    - go
    - gopls
    - goreleaser
    - gpg
    - groff
    - grep
    - gzip
    - hadolint
    - harfbuzz
    - hdf5
    - htop
    - hugo
    - hunspell
    - igv
    - imagemagick
    - jq
    - jsonlint
    - kompose
    - kubectl
    - leveldb
    - libgit2
    - libjpeg
    - librsvg
    - libssh2
    - libtiff
    - libxml2
    - little-cms2
    - llvm
    - lmdb
    - lua
    - luajit
    - md5sha1sum
    - mercurial
    - ncdu
    - nkf
    - nmap
    - node
    - npm
    - open-mpi
    - opencv
    - openjdk
    - openssl
    - p7zip
    - pandoc
    - parallel
    - pbzip2
    - pdf2svg
    - picard-tools
    - pigz
    - pkg-config
    - postgresql
    - protobuf
    - python3
    - quicktype
    - rain
    - readline
    - redis
    - rename
    - ruby
    - rust
    - rustup
    - samtools
    - sbt
    - scala
    - screen
    - shellcheck
    - shunit2
    - snappy
    - sqlite
    - supervisor
    - szip
    - terraform
    - tig
    - tldr
    - tmux
    - tree
    - v8
    - wakeonlan
    - watch
    - wdiff
    - webp
    - wget
    - xml2
    - yarn
    - zip
    - zlib
    - zsh
brew_cask_packages:
  - adobe-acrobat-reader
  - amazon-music
  - chrome-remote-desktop-host
  - deepl
  - discord
  - docker
  - drawio
  - dropbox
  - endnote
  - firefox
  - gimp
  - google-drive
  - google-chrome
  - google-cloud-sdk
  - google-japanese-ime
  - handbrake
  - igv
  - iterm2
  - kindle
  - microsoft-edge
  - microsoft-office
  - microsoft-remote-desktop
  - opera-neon
  - r
  - rstudio
  - session-manager-plugin
  - slack
  - visual-studio-code
  - xquartz
  - zoom
