---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy }}
      no_proxy={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/yum.conf
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/yum.conf
    state: present
    block: |
      proxy={{ http_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Add EPEL YUM repo
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  notify: Notify updates of the system via Slack

- name: Add EPEL Vim repo
  become: true
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/mcepl/vim8/repo/epel-7/mcepl-vim8-epel-7.repo
    dest: /etc/yum.repos.d/mcepl-vim8-epel-7.repo
  notify: Notify updates of the system via Slack

- name: Add Docker repo
  become: true
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  notify: Notify updates of the system via Slack

- name: Add Kubernetes repo
  become: true
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  yum:
    update_cache: yes
    name: '*'
    state: latest
  notify: Notify updates of the system via Slack

- name: Install packages
  when: yum_packages is defined
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - device-mapper-persistent-data
    - git
    - lvm2
    - sudo
    - yum-utils
    - "{{ yum_packages }}"
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Check installed Docker CE
  become: true
  yum:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Uninstall old versions of Docker
  when: docker_ce_installed is failed
  become: true
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine

- name: Install Docker CE
  when: docker_ce_installed is failed
  become: true
  yum:
    name: docker-ce
    state: latest
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Install Kubernetes
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - flannel
    - kubeadm
    - kubectl
    - kubelet
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
