---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/yum.conf
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/yum.conf
    state: present
    block: |
      proxy={{ https_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Add EPEL YUM repo
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  notify: Notify updates of the system via Slack

- name: Add Docker repo
  become: true
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest
  notify:
    - Clean yum
    - Notify updates of the system via Slack

- name: Install packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-engine
    - docker-python
    - git
    - sudo
    - "{{ yum_packages }}"
  ignore_errors: true
  notify:
    - Clean yum
    - Notify updates of the system via Slack

- name: Set users
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
