---
- name: Add http_proxy to /etc/environment
  when: use_proxy
  become: true
  lineinfile:
    create: yes
    dest: /etc/environment
    regexp: "{{ item.regexp }}"
    state: present
    line: "{{ item.line }}"
  with_items:
    - regexp: '^HTTP_PROXY'
      line: 'HTTP_PROXY={{ http_proxy }}'
    - regexp: '^HTTPS_PROXY'
      line: 'HTTPS_PROXY={{ https_proxy }}'
    - regexp: '^NO_PROXY'
      line: 'NO_PROXY={{ no_proxy }}'
  notify: Notify updates of the system via Slack

- name: Add proxy to /etc/yum.conf
  when: use_proxy
  become: true
  lineinfile:
    create: yes
    dest: /etc/yum.conf
    regexp: '^proxy='
    state: present
    line: 'proxy={{ https_proxy }}'
    notify: Notify updates of the system via Slack

- name: Add EPEL YUM repo
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  notify: Notify updates of the system via Slack

- name: Add Docker repo
  become: true
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest
  notify: Notify updates of the system via Slack

- name: Install packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-engine
    - git
    - python34-pip
    - sudo
    - "{{ yum_packages }}"
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when:
    - enable_nopass_sudo is defined
    - enable_nopass_sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel  ALL=(ALL)       NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Set users
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack

- name: Install packages via pip3
  become: true
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
    state: latest
  with_items:
    - docker
    - docker-compose
  notify: Notify updates of the system via Slack
