---
- name: Build and deploy AWX
  hosts: awx
  roles:
    - role: submodules/awx/installer/roles/check_vars
    - role: submodules/awx/installer/roles/image_build
      when: dockerhub_base is not defined
    - role: submodules/awx/installer/roles/image_push
      when: docker_registry is defined and dockerhub_base is not defined
    - role: submodules/awx/installer/roles/kubernetes
      when: openshift_host is defined or kubernetes_context is defined
    - role: submodules/awx/installer/roles/local_docker
      when: openshift_host is not defined and kubernetes_context is not defined
