---
- name: Set up development servers with sudo
  hosts: dev
  vars:
    use_proxy: "{{ http_proxy is defined }}"
    enable_nopass_sudo: false
  environment:
    http_proxy: "{{ http_proxy if http_proxy is defined else '' }}"
    https_proxy: "{{ https_proxy if https_proxy is defined else '' }}"
    no_proxy: "{{ no_proxy if no_proxy is defined else '' }}"
  roles:
    - role: fedora
      when: ansible_distribution == 'Fedora'
    - role: centos
      when: ansible_distribution == 'CentOS'
    - role: ubuntu
      when: ansible_distribution == 'Ubuntu'
    - role: arm-debian
      when:
        - ansible_architecture in ['armv6l', 'armv7l']
        - ansible_distribution == 'Debian'

- name: Set up container environments
  hosts: dev
  vars_files:
    - group_vars/container.yml
  vars:
    ignore_running_containers: true
    use_proxy: "{{ http_proxy is defined }}"
  environment:
    http_proxy: "{{ http_proxy if http_proxy is defined else '' }}"
    https_proxy: "{{ https_proxy if https_proxy is defined else '' }}"
    no_proxy: "{{ no_proxy if no_proxy is defined else '' }}"
  roles:
    - role: submodules/ansible-container-engine/roles/docker
      when: ansible_os_family in ['RedHat', 'Debian']
    - role: submodules/ansible-container-engine/roles/kubernetes
      when: ansible_os_family in ['RedHat', 'Debian']

- name: Set up development servers
  hosts: dev
  vars:
    use_proxy: "{{ http_proxy is defined }}"
  environment:
    http_proxy: "{{ http_proxy if http_proxy is defined else '' }}"
    https_proxy: "{{ https_proxy if https_proxy is defined else '' }}"
    no_proxy: "{{ no_proxy if no_proxy is defined else '' }}"
  roles:
    - role: macos
      when: ansible_distribution == 'MacOSX'
    - role: cli
    - role: vim
    - role: python
    - role: ruby
    - role: go
    - role: r
