---
- name: Set up development servers with sudo
  hosts: dev_sudo
  vars:
    use_proxy: false
    enable_nopass_sudo: true
  roles:
    - role: fedora
      when: ansible_distribution == 'Fedora'
    - role: centos
      when: ansible_distribution == 'CentOS'
    - role: ubuntu
      when: ansible_distribution == 'Ubuntu'
    - role: arm-debian
      when:
        - ansible_architecture in ['armv6l', 'armv7l']
        - ansible_distribution == 'Debian'
    - role: submodules/ansible-container-engine/roles/docker
      when: ansible_os_family in ['RedHat', 'Debian']
    - role: submodules/ansible-container-engine/roles/kubernetes
      when: ansible_os_family in ['RedHat', 'Debian']

- name: Set up development servers
  hosts: dev
  vars:
    use_proxy: false
  roles:
    - role: macos
      when: ansible_distribution == 'MacOSX'
    - role: cli
    - role: vim
    - role: python
    - role: ruby
    - role: go
    - role: r
