---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/dnf/dnf.conf
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/dnf/dnf.conf
    state: present
    block: |
      proxy={{ http_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  dnf:
    name: '*'
    state: latest
  notify:
    - Clean dnf
    - Notify updates of the system via Slack

- name: Install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnf-plugins-core
    - git
    - sudo
    - "{{ dnf_packages }}"
  notify:
    - Clean dnf
    - Notify updates of the system via Slack

- name: Check installed Docker CE
  become: true
  dnf:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Uninstall old versions of Docker
  when: docker_ce_installed|failed
  become: true
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: Set up the Docker CE repository
  when: docker_ce_installed|failed
  become: true
  shell: |
    dnf config-manager --add-repo \
      https://download.docker.com/linux/fedora/docker-ce.repo
    dnf makecache fast

- name: Install Docker CE
  when: docker_ce_installed|failed
  become: true
  dnf:
    name: docker-ce
    state: latest
  notify:
    - Clean dnf
    - Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
