---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/dnf/dnf.conf
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/dnf/dnf.conf
    state: present
    block: |
      proxy={{ http_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  dnf:
    name: '*'
    state: latest
  notify:
    - Clean dnf
    - Notify updates of the system via Slack

- name: Install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - sudo
    - "{{ dnf_packages }}"
  ignore_errors: true
  notify:
    - Clean dnf
    - Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
