---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy }}
      no_proxy={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/dnf/dnf.conf
  when: use_proxy
  become: true
  blockinfile:
    dest: /etc/dnf/dnf.conf
    state: present
    block: |
      proxy={{ http_proxy }}
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  dnf:
    name: '*'
    state: latest
  notify: Notify updates of the system via Slack

- name: Install packages
  when: dnf_packages is defined
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnf-plugins-core
    - git
    - libselinux-python   # requied to be preinstalled
    - redhat-rpm-config
    - sudo
    - zsh
    - "{{ dnf_packages }}"
  notify: Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
