---
- name: Clone pyenv
  ansible.builtin.git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    force: yes
  notify: Notify updates of Python via Slack

- name: Set variables
  ansible.builtin.set_fact:
    pyenv: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
    pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
    n_versions_to_install: 2
    base_requirements: "{{ lookup('file', 'requirements.txt').split('\n') }}"

- name: Fetch the latest versions of Python
  ansible.builtin.script:
    cmd: >
      install_pyenv.sh --print-stable-versions {{ n_versions_to_install }}
    executable: /bin/bash
  changed_when: false
  register: py_v

- name: Check if the latest versions are installed
  ansible.builtin.stat:
    path: "{{ pyenv_root }}/versions/{{ item }}/bin/python"
  loop: "{{ py_v.stdout_lines }}"
  register: py_x

- name: Set a list for new versions to install
  set_fact:
    new_v: |
      {% set o = [] %}
      {% for p in py_x.results if not p.stat.exists %}
      {%   set _ = o.append(p.item.stdout) %}
      {% endfor %}
      {{ o }}

- name: Install the latest versions of Python
  when:
    - new_v|length > 0
  ansible.builtin.script:
    cmd: >
      install_pyenv.sh {{ item }}
    executable: /bin/bash
  loop: "{{ new_v }}"
  notify: Notify updates of Python via Slack

- name: Install and update base packages
  ansible.builtin.pip:
    name: "{{ base_requirements }}"
    executable: "{{ pyenv_root }}/versions/{{ item }}/bin/pip"
    state: latest
  loop: "{{ py_v.stdout_lines }}"
  notify: Notify updates of Python via Slack

- name: Install and update Python packages
  when:
    - pip_packages is defined
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    executable: "{{ pyenv_root }}/versions/{{ item }}/bin/pip"
    state: latest
  loop: "{{ py_v.stdout_lines }}"
  ignore_errors: true
  notify: Notify updates of Python via Slack
