---
- name: Clone pyenv
  git:
    repo: 'https://github.com/yyuu/pyenv.git'
    dest: "{{ ansible_env.HOME }}/.pyenv"
  notify: Notify updates of Python via Slack

- name: Set variables
  set_fact:
    pyenv: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
    pyenv_python: "{{ ansible_env.HOME }}/.pyenv/shims/python"
    pyenv_pip: "{{ ansible_env.HOME }}/.pyenv/shims/pip"

- name: Fetch the latest version
  shell: |
    {{ pyenv }} install --list \
      | awk '$1 ~ /^{{ python_version }}\.[0-9]+\.[0-9]+$/ { v=$1 } END{ print v }'
  register: python_v

- name: Check installed versions
  shell: |
    {{ pyenv }} versions \
      | grep -ce '\s{{ python_v.stdout }}'
  register: python_v_installed
  ignore_errors: true

- name: Install Python
  when: python_v_installed.stdout|int == 0
  shell: |
    {{ pyenv }} install {{ python_v.stdout }}
  register: install_python
  ignore_errors: true
  notify: Notify updates of Python via Slack

- name: Set the global version
  when: python_v_installed.stdout|int > 0 or install_python|success
  shell: |
    {{ pyenv }} global {{ python_v.stdout }}
  register: set_global_python
  notify: Notify updates of Python via Slack

- name: Install and update packages
  when: set_global_python|success
  pip:
    name: "{{ item }}"
    executable: "{{ pyenv_pip }}"
    state: latest
  with_items:
    - "{{ pip_packages }}"
  ignore_errors: true
  notify: Notify updates of Python via Slack
