---
- name: Clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    force: yes
  notify: Notify updates of Python via Slack

- name: Set variables
  set_fact:
    pyenv: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
    pyenv_root: "{{ ansible_env.HOME }}/.pyenv"

- name: Fetch the latest versions
  shell: |
    {{ pyenv }} install --list \
      | awk '$1 ~ /^{{ item }}[\.\-0-9]+$/ { v=$1 } END { print v }'
  with_items:
    - 3
  changed_when: false
  register: py_v

- name: Check if the latest versions exist
  stat:
    path: "{{ pyenv_root }}/versions/{{ item.stdout }}/bin/python"
  with_items: "{{ py_v.results }}"
  register: py_x

- name: Set a list for new versions to install
  set_fact:
    new_v: |
      {% set o = [] %}
      {% for p in py_x.results if not p.stat.exists %}
      {%   set _ = o.append(p.item.stdout) %}
      {% endfor %}
      {{ o }}

- name: Install the latest versions
  when: new_v|length > 0
  script: |
    install_pyenv.sh {{ item }}
  with_items: "{{ new_v }}"
  ignore_errors: true
  notify: Notify updates of Python via Slack

- name: Check if pip exists
  stat:
    path: "{{ pyenv_root }}/versions/{{ item.stdout }}/bin/pip"
  with_items: "{{ py_v.results }}"
  register: pip_x

- name: Install and update base packages
  when:
    - pip_x.results[0].stat.exists
    - pip_packages is defined
    - pip_packages[3] is defined
  pip:
    name:
      - ansible-lint
      - bandit
      - csvkit
      - docopt
      - flake8
      - flake8-bugbear
      - flake8-isort
      - flake8-pyproject
      - grip
      - jupyter
      - mypy
      - pandas
      - pep8-naming
      - pip
      - pipx
      - poetry
      - pynvim
      - pyright
      - ruff
      - vim-vint
      - vulture
      - yamllint
    executable: "{{ pip_x.results[0].stat.path }}"
    state: latest
  ignore_errors: true
  notify: Notify updates of Python via Slack

- name: Install and update Python packages
  when:
    - pip_x.results[0].stat.exists
    - pip_packages is defined
    - pip_packages[3] is defined
  pip:
    name: "{{ pip_packages[3] }}"
    executable: "{{ pip_x.results[0].stat.path }}"
    state: latest
  ignore_errors: true
  notify: Notify updates of Python via Slack
