---
- name: Update homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  notify:
    - Clean homebrew
    - Notify updates of the system via Slack

- name: Tap repositories
  when:
    - brew_packages is defined
    - brew_packages.from_third_party_repos is defined
  homebrew_tap:
    name: "{{ item.tap }}"
    state: present
  with_items: "{{ brew_packages.from_third_party_repos }}"
  notify: Notify updates of the system via Slack

- name: Install packages using casks
  when: brew_cask_packages is defined
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_cask_packages }}"
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Install packages
  when:
    - brew_packages is defined
    - brew_packages.without_options is defined
  homebrew:
    name: "{{ brew_packages.without_options }}"
    state: latest
  ignore_errors: true
  notify:
    - Clean homebrew
    - Notify updates of the system via Slack

- name: Install tap packages
  when:
    - brew_packages is defined
    - brew_packages.from_third_party_repos is defined
  homebrew:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ brew_packages.from_third_party_repos }}"
  ignore_errors: true
  notify:
    - Clean homebrew
    - Notify updates of the system via Slack

- name: Install packages with options
  when:
    - brew_packages is defined
    - brew_packages.with_options is defined
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.options }}"
    state: latest
  with_items: "{{ brew_packages.with_options }}"
  ignore_errors: true
  notify:
    - Clean homebrew
    - Notify updates of the system via Slack
