python_version: 3
pip_packages:
  - awscli
  - beautifulsoup4
  - bottle
  - csvkit
  - cython
  - docker
  - docker-compose
  - fabric
  - feather-format
  - flake8
  - ggplot
  - grip
  - ipykernel
  - ipython
  - jupyter
  - keras
  - luigi
  - matplotlib
  - mechanize
  - mock
  - mxnet
  - nose
  - numpy
  - pandas
  - pycuda
  - pymc
  - pyper
  - pystan
  - pytest
  - pytoml
  - pyyaml
  - redis
  - requests
  - requests_oauthlib
  - scikit-learn
  - scipy
  - scss
  - seaborn
  - selenium
  - setuptools
  - six
  - sphinx
  - sympy
  - tensorflow
  - tensorflow-gpu
  - testfixtures
  - theano
  - tornado
  - tox
  - twitter
  - virtualenv
  - webtest
