---
- name: Upgrade all packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Install packages
  when: apt_packages is defined
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - aptitude
    - ca-certificates
    - git
    - software-properties-common
    - sudo
    - "{{ apt_packages }}"
  ignore_errors: true
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
