---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    create: yes
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy }}
      no_proxy={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/apt/apt.conf
  when: use_proxy
  become: true
  blockinfile:
    create: yes
    dest: /etc/apt/apt.conf
    state: present
    block: |
      Acquire::http::proxy "{{ http_proxy }}";
      Acquire::https::proxy "{{ https_proxy }}";
  notify: Notify updates of the system via Slack

- name: Add %wheel
  when: enable_nopass_sudo
  become: true
  group:
    name: wheel
    state: present
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Install required packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - aptitude
    - ca-certificates
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Add the GPG key for Docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present
  notify: Notify updates of the system via Slack

- name: Add Docker repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  notify: Notify updates of the system via Slack

- name: Add the GPG key for Kubernetes
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  notify: Notify updates of the system via Slack

- name: Add Kubernetes repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
    state: present
    filename: kubernetes
  notify: Notify updates of the system via Slack

- name: Add the GPG key for R
  become: true
  apt_key:
    id: E084DAB9
    keyserver: keyserver.ubuntu.com
  notify: Notify updates of the system via Slack

- name: Add R repo
  become: true
  apt_repository:
    repo: "deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}/"
    state: present
    filename: r
  notify: Notify updates of the system via Slack

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - software-properties-common
    - sudo
    - "{{ apt_packages }}"
  ignore_errors: true
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Check installed Docker CE
  become: true
  apt:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Uninstall old versions of Docker
  when: docker_ce_installed is failed
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Install Docker CE
  when: docker_ce_installed is failed
  become: true
  apt:
    name: docker-ce
    state: latest
  ignore_errors: true
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack

- name: Install Kubernetes
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  ignore_errors: true
  notify:
    - Remove useless and unneeded packages
    - Notify updates of the system via Slack
