---
- name: Set proxy at /etc/environment
  when: use_proxy
  become: true
  blockinfile:
    create: yes
    dest: /etc/environment
    state: present
    block: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ https_proxy }}
      NO_PROXY={{ no_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ https_proxy }}
      no_proxy={{ no_proxy }}
  notify: Notify updates of the system via Slack

- name: Set proxy at /etc/apt/apt.conf
  when: use_proxy
  become: true
  blockinfile:
    create: yes
    dest: /etc/apt/apt.conf
    state: present
    block: |
      Acquire::http::proxy "{{ http_proxy }}";
      Acquire::https::proxy "{{ https_proxy }}";
  notify: Notify updates of the system via Slack

- name: Add %wheel
  when: enable_nopass_sudo
  become: true
  group:
    name: wheel
    state: present
  notify: Notify updates of the system via Slack

- name: Write %wheel in /etc/sudoers
  when: enable_nopass_sudo
  become: true
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: |
      %wheel  ALL=(ALL)       NOPASSWD: ALL
    validate: 'visudo -cf %s'
  notify: Notify updates of the system via Slack

- name: Install required packages
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - aptitude
    - ca-certificates
  notify: Notify updates of the system via Slack

- name: Add Vim repo
  become: true
  apt_repository:
    repo: ppa:jonathonf/vim
  notify: Notify updates of the system via Slack

- name: Add the GPG key for R
  become: true
  apt_key:
    id: E084DAB9
    keyserver: keyserver.ubuntu.com
  notify: Notify updates of the system via Slack

- name: Add R repo
  when: ansible_distribution_release != 'bionic'
  become: true
  apt_repository:
    repo: "deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}/"
    state: present
    filename: r
  notify: Notify updates of the system via Slack

- name: Upgrade all packages
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: yes
    update_cache: yes
  notify: Notify updates of the system via Slack

- name: Install packages
  when: apt_packages is defined
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - software-properties-common
    - sudo
    - "{{ apt_packages }}"
  ignore_errors: true
  notify: Notify updates of the system via Slack

- name: Set users
  when: users is defined
  become: true
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items: "{{ users }}"
  notify: Notify updates of the system via Slack
