---
- name: Set variables
  set_fact:
    path:  "{{ ansible_env.PATH }}:/usr/local/bin"
    gopath: "{{ ansible_env.HOME }}/.go"

- name: Check go command
  environment:
    PATH: "{{ path }}"
  shell: |
    go version
  changed_when: False

- name: Create .go
  file:
    path: "{{ gopath }}"
    state: directory
  register: mkdir_go

- name: Update packages
  when: mkdir_go|changed
  environment:
    PATH: "{{ path }}"
    GOPATH: "{{ gopath }}"
  shell: |
    go get -u all
  ignore_errors: true
  notify: Notify updates of Go via Slack

- name: Install packages
  environment:
    PATH: "{{ path }}"
    GOPATH: "{{ gopath }}"
  shell: |
    go get -v {{ item }}
  with_items: "{{ go_packages }}"
  ignore_errors: true
  notify: Notify updates of Go via Slack
