---
- name: Check installed Docker CE in Ubuntu or Debian
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Check installed Docker CE in Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  dnf:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Check installed Docker CE in CentOS
  when: ansible_distribution == 'CentOS'
  become: true
  yum:
    name: docker-ce
    state: present
  ignore_errors: true
  register: docker_ce_installed

- name: Create docker.service.d/
  when:
    - docker_ce_installed|succeeded
    - use_proxy
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Put /etc/systemd/system/docker.service.d/option.conf
  when:
    - docker_ce_installed|succeeded
    - use_proxy
  become: true
  template:
    src: option.conf.j2
    dest: /etc/systemd/system/docker.service.d/option.conf
  notify:
    - Restart Docker
    - Notify updates of Docker via Slack

- name: Start and enable Docker
  when: docker_ce_installed|succeeded
  become: true
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: true
  notify: Notify updates of Docker via Slack

- name: Pull images
  when: docker_ce_installed|succeeded
  become: true
  docker_image:
    name: "{{ item }}"
  with_items: "{{ docker_images }}"
  ignore_errors: true
  notify: Notify updates of Docker via Slack

- name: Add %docker
  when:
    - docker_ce_installed|succeeded
    - docker_users is defined
  become: true
  group:
    name: docker
    state: present
  notify: Notify updates of Docker via Slack

- name: Add users to %docker
  when:
    - docker_ce_installed|succeeded
    - docker_users is defined
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  notify: Notify updates of Docker via Slack
