---
- name: Create docker.service.d/
  when: use_proxy
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Put /etc/systemd/system/docker.service.d/option.conf
  when: use_proxy
  become: true
  template:
    src: option.conf.j2
    dest: /etc/systemd/system/docker.service.d/option.conf
  notify:
    - Restart Docker
    - Notify updates of Docker via Slack

- name: Start and enable Docker
  become: true
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: true
  notify: Notify updates of Docker via Slack

- name: Pull images
  become: true
  docker_image:
    name: "{{ item }}"
  with_items: "{{ docker_images }}"
  ignore_errors: true
  notify: Notify updates of Docker via Slack

- name: Add %docker
  when: docker_users is defined
  become: true
  group:
    name: docker
    state: present
  notify: Notify updates of Docker via Slack

- name: Add users to %docker
  when: docker_users is defined
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  notify: Notify updates of Docker via Slack
