---
- name: Clone rbenv
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: 'https://github.com/rbenv/rbenv.git'
      dest: "{{ ansible_env.HOME }}/.rbenv"
    - repo: 'https://github.com/rbenv/ruby-build.git'
      dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
  notify: Notify updates of Ruby via Slack

- name: Set variables
  set_fact:
    rbenv: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv"
    rbenv_ruby: "{{ ansible_env.HOME }}/.rbenv/shims/ruby"
    rbenv_gem: "{{ ansible_env.HOME }}/.rbenv/shims/gem"

- name: Fetch the latest version
  shell: |
    {{ rbenv }} install --list \
      | awk '$1 ~ /^{{ ruby_version }}\.[0-9]+\.[0-9]+$/ { v=$1 } END{ print v }'
  register: ruby_v

- name: Check installed versions
  shell: |
    {{ rbenv }} versions \
      | grep -ce '\s{{ ruby_v.stdout }}'
  register: ruby_v_installed
  ignore_errors: true

- name: Install Ruby
  when: ruby_v_installed.stdout|int == 0
  shell: |
    {{ rbenv }} install {{ ruby_v.stdout }}
  register: install_ruby
  ignore_errors: true
  notify: Notify updates of Ruby via Slack

- name: Set the global version
  when: ruby_v_installed.stdout|int > 0 or install_ruby|success
  shell: |
    {{ rbenv }} global {{ ruby_v.stdout }}
  register: set_global_ruby
  notify: Notify updates of Ruby via Slack

- name: Install and update packages
  when: set_global_ruby|success
  gem:
    name: "{{ item }}"
    executable: "{{ rbenv_gem }}"
    state: latest
  with_items: "{{ gem_packages }}"
  ignore_errors: true
  notify: Notify updates of Ruby via Slack
