---
- name: Clone rbenv
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: 'https://github.com/rbenv/rbenv.git'
      dest: "{{ ansible_env.HOME }}/.rbenv"
    - repo: 'https://github.com/rbenv/ruby-build.git'
      dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
  notify: Notify updates of Ruby via Slack

- name: Set variables
  set_fact:
    rbenv: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv"
    rbenv_ruby: "{{ ansible_env.HOME }}/.rbenv/shims/ruby"
    rbenv_gem: "{{ ansible_env.HOME }}/.rbenv/shims/gem"

- name: Fetch the latest version
  shell: |
    {{ rbenv }} install --list | awk '$1 ~ /^2\.[0-9]+\.[0-9]+$/ { v=$1 } END{ print v }'
  register: ruby_v

- name: Install Ruby
  shell: |
    {{ rbenv }} versions | grep -e ' {{ ruby_v.stdout }}' || {{ rbenv }} install {{ ruby_v.stdout }}
  ignore_errors: true
  notify: Notify updates of Ruby via Slack

- name: Set the global version
  shell: |
    {{ rbenv }} global {{ ruby_v.stdout }}
  ignore_errors: true
  register: set_ruby

- name: Install and update packages
  when: set_ruby|success
  gem:
    name: "{{ item }}"
    executable: "{{ rbenv_gem }}"
    state: latest
  with_items: "{{ gem_packages }}"
  ignore_errors: true
  notify: Notify updates of Ruby via Slack
