---
- name: Configure git
  when:
    - git_user_name is defined
    - git_user_email is defined
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: color.ui
      value: true
    - name: push.default
      value: matching
    - name: user.name
      value: "{{ git_user_name }}"
    - name: user.email
      value: "{{ git_user_email }}"
  notify: Notify updates of CLI via Slack

- name: Set proxy for git
  when: use_proxy
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: http.proxy
      value: "{{ http_proxy }}"
    - name: https.proxy
      value: "{{ https_proxy }}"
  notify: Notify updates of CLI via Slack

- name: Put ~/.zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
  notify: Notify updates of CLI via Slack

- name: Set proxy at ~/.zprofile
  when: use_proxy
  blockinfile:
    create: yes
    dest: "{{ ansible_env.HOME }}/.zprofile"
    insertafter: '# proxy'
    state: present
    block: |
      export HTTP_PROXY='{{ http_proxy }}'
      export HTTPS_PROXY='{{ https_proxy }}'
      export NO_PROXY='{{ no_proxy }}'
      export http_proxy="${HTTP_PROXY}"
      export https_proxy="${HTTP_PROXY}"
      export no_proxy="${NO_PROXY}"
  notify: Notify updates of CLI via Slack

- name: Put ~/.vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  notify: Notify updates of CLI via Slack

- name: Create ~/.vim/bundles/
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundles"
    state: directory
  register: create_vim_dirs
  notify: Notify updates of CLI via Slack

- name: Clone dein.vim
  git:
    repo: https://github.com/Shougo/dein.vim
    dest: "{{ ansible_env.HOME }}/.vim/bundles/repos/github.com/Shougo/dein.vim"
  notify: Notify updates of CLI via Slack

- name: Install dein.vim
  when: create_vim_dirs is changed
  shell: |
    ~/.vim/bundles/repos/github.com/Shougo/dein.vim/bin/installer.sh ~/.vim/bundles
  ignore_errors: true
  notify: Notify updates of CLI via Slack

- name: Install Vim plugins
  shell: |
    vim -c 'try | call dein#update() | finally | qall! | endtry' \
      -N -u ${HOME}/.vimrc -U NONE -i NONE -V1 -e -s
  ignore_errors: true
  notify: Notify updates of CLI via Slack
