---
- name: Configure git
  when:
    - git_user_name is defined
    - git_user_email is defined
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: color.ui
      value: true
    - name: push.default
      value: matching
    - name: user.name
      value: "{{ git_user_name }}"
    - name: user.email
      value: "{{ git_user_email }}"
  notify: Notify updates of CLI via Slack

- name: Put ~/.zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
  notify: Notify updates of CLI via Slack

- name: Set proxy at ~/.zprofile
  when: use_proxy
  blockinfile:
    create: yes
    dest: "{{ ansible_env.HOME }}/.zprofile"
    insertafter: '# proxy'
    state: present
    block: |
      export HTTP_PROXY='{{ http_proxy }}'
      export HTTPS_PROXY='{{ https_proxy }}'
      export NO_PROXY='{{ no_proxy }}'
      export http_proxy="${HTTP_PROXY}"
      export https_proxy="${HTTP_PROXY}"
      export no_proxy="${NO_PROXY}"
  notify: Notify updates of CLI via Slack

- name: Put ~/.vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  notify: Notify updates of CLI via Slack

- name: Create ~/.vim/bundle/
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundle"
    state: directory

- name: Clone vimproc.vim
  git:
    repo: 'https://github.com/Shougo/vimproc.vim.git'
    dest: "{{ ansible_env.HOME }}/.vim/bundle/vimproc.vim"
  register: update_vimproc
  notify: Notify updates of CLI via Slack

- name: Clone neobundle.vim
  git:
    repo: 'https://github.com/Shougo/neobundle.vim.git'
    dest: "{{ ansible_env.HOME }}/.vim/bundle/neobundle.vim"
  register: update_neobundle
  notify: Notify updates of CLI via Slack

- name: Make vimproc.vim
  when: update_vimproc|changed
  make:
    chdir: "{{ ansible_env.HOME }}/.vim/bundle/vimproc.vim"

- name: Install Vim plugins
  shell: |
    {{ ansible_env.HOME }}/.vim/bundle/neobundle.vim/bin/neoinstall
  notify: Notify updates of CLI via Slack
