---
- name: Configure git
  when:
    - git_user_name is defined
    - git_user_email is defined
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: color.ui
      value: true
    - name: push.default
      value: matching
    - name: user.name
      value: "{{ git_user_name }}"
    - name: user.email
      value: "{{ git_user_email }}"
  notify: Notify updates of CLI via Slack

- name: Set .zshrc
  file:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
  notify: Notify updates of CLI via Slack

- name: Set .vimrc
  file:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  notify: Notify updates of CLI via Slack

- name: Create .vim/bundle/
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundle"
    state: directory

- name: Clone vimproc.vim
  git:
    repo: "{{ ansible_env.HOME }}/.vim/bundle/vimproc.vim"
    dest: 'https://github.com/Shougo/vimproc.vim.git'
  register: update_vimproc
  notify: Notify updates of CLI via Slack

- name: Clone neobundle.vim
  git:
    repo: "{{ ansible_env.HOME }}/.vim/bundle/neobundle.vim"
    dest: 'https://github.com/Shougo/neobundle.vim.git'
  register: update_neobundle
  notify: Notify updates of CLI via Slack

- name: Make vimproc
  when: update_vimproc|changed
  make:
    chdir: "{{ ansible_env.HOME }}/.vim/bundle/vimproc.vim"

- name: Install Vim plugins
  shell: |
    {{ ansible_env.HOME }}/.vim/bundle/neobundle.vim/bin/neoinstall
  notify: Notify updates of CLI via Slack
